// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TavernaWeb.Persistence.Context;

#nullable disable

namespace TavernaWeb.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TavernaWeb.Domain.Models.Ficha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Sistema")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Fichas", (string)null);
                });

            modelBuilder.Entity("TavernaWeb.Domain.Models.Ordem", b =>
                {
                    b.Property<int>("Idficha")
                        .HasColumnType("int");

                    b.Property<int>("Agilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Inteligencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Nex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Origem")
                        .HasColumnType("int");

                    b.Property<int>("Pe")
                        .HasColumnType("int");

                    b.Property<int>("Presenca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SubClasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Vida")
                        .HasColumnType("int");

                    b.Property<int>("Vigor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Idficha");

                    b.ToTable("FichasOrdem", (string)null);
                });

            modelBuilder.Entity("TavernaWeb.Domain.Models.Pericia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Idficha")
                        .HasColumnType("int");

                    b.Property<int>("Nome")
                        .HasColumnType("int");

                    b.Property<int>("ValorBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Idficha");

                    b.ToTable("Pericias", (string)null);
                });

            modelBuilder.Entity("TavernaWeb.Domain.Models.Poderes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustoPe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Idficha")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(420)
                        .HasColumnType("nvarchar(420)");

                    b.HasKey("Id");

                    b.HasIndex("Idficha");

                    b.ToTable("Poderes", (string)null);
                });

            modelBuilder.Entity("TavernaWeb.Domain.Models.Ordem", b =>
                {
                    b.HasOne("TavernaWeb.Domain.Models.Ficha", null)
                        .WithOne()
                        .HasForeignKey("TavernaWeb.Domain.Models.Ordem", "Idficha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TavernaWeb.Domain.Models.Pericia", b =>
                {
                    b.HasOne("TavernaWeb.Domain.Models.Ordem", null)
                        .WithMany("Pericias")
                        .HasForeignKey("Idficha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TavernaWeb.Domain.Models.Poderes", b =>
                {
                    b.HasOne("TavernaWeb.Domain.Models.Ordem", null)
                        .WithMany("Poderes")
                        .HasForeignKey("Idficha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TavernaWeb.Domain.Models.Ordem", b =>
                {
                    b.Navigation("Pericias");

                    b.Navigation("Poderes");
                });
#pragma warning restore 612, 618
        }
    }
}
